name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - name: Install deps and run tests
      run: |
        npm ci
        npm test
      env:
        CI: true
